module.exports = {
    SECRET_KEY_STRIPE: "sk_test_JFlP6I3IseQdbqWYmAhE93vh00iVqllbei",
    CONNECTION_STRING: "mongodb+srv://dbCafocc:dbcafocc@cafocc-iax21.gcp.mongodb.net/hacademy?retryWrites=true&w=majority",
    JWT_SECRET: process.env.JWT_SECRET || "jwt_secret",
    GOOGLE_CLIENT_ID: "225505233278-e8b875jlitd5dluj706bvrjh2c0emjr3.apps.googleusercontent.com",
    GOOGLE_CLIENT_SECRET: "WIndolH3T-1vMAkM1NR8GLru",
    FACEBOOK_CLIENT_ID: "291773038524316",
    FACEBOOK_CLIENT_SECRET: "bc1e439dbee20816c59c0c4145d269c9",
    USERNAME_EMAIL: 'dhtc.kltn@gmail.com',
    PASSWORD_EMAIL: 'HaiTom!1',
    EMAIL_SECRET: "email_secret",
    PAGE_ACCESS_TOKEN: "EAAEJXbRQ95wBALO2qEnFrMca1bMKrOZA4HG6lz7BZAAdx6na4qLJzRREqZBjBny0edBnNstaAulcXvok60Om2d5mVedL0g1Yb6LPeXMeZBh10XZCsXq6qpRVor6Kand28cWNpD5RgbniryR5fgSiREjBjRuBXU2Naq9aAucd8tehOpG5T6h3x",
    PLATFORM_FACEBOOK_URL: "https://graph.facebook.com/v7.0",
    // URL_CLIENT: "https://localhost:3001",
    // URL_ADMIN: "https://localhost:3002",
    // URL: "http://localhost:3000",
    URL: "https://hacademy-api.herokuapp.com",
    URL_CLIENT: "https://cafocc.web.app",
    URL_ADMIN: "https://cafocc-cms.web.app",
}
